// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_proje.Data;

#nullable disable

namespace web_proje.Migrations
{
    [DbContext(typeof(VeritabaniContext))]
    [Migration("20241211091805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_proje.Entity.Acil_Durum", b =>
                {
                    b.Property<int>("Acil_DurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Acil_DurumId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Acil_DurumId");

                    b.ToTable("Acil_Durumlar");
                });

            modelBuilder.Entity("web_proje.Entity.Asistan", b =>
                {
                    b.Property<int>("AsistanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistanId"));

                    b.Property<string>("AsistanAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsistanMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsistanSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AsistanTel")
                        .HasColumnType("bigint");

                    b.Property<int>("AsistanYas")
                        .HasColumnType("int");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Nobet_Tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("AsistanId");

                    b.ToTable("Asistanlar");
                });

            modelBuilder.Entity("web_proje.Entity.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumId"));

                    b.Property<string>("BolumAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bos_Yatak_Sayisi")
                        .HasColumnType("int");

                    b.Property<int>("Hasta_Sayisi")
                        .HasColumnType("int");

                    b.HasKey("BolumId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("web_proje.Entity.Hoca", b =>
                {
                    b.Property<int>("HocaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HocaId"));

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("HocaAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocaMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocaSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HocaTel")
                        .HasColumnType("bigint");

                    b.Property<int>("HocaYas")
                        .HasColumnType("int");

                    b.HasKey("HocaId");

                    b.ToTable("Hocalar");
                });

            modelBuilder.Entity("web_proje.Entity.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("KullaniciAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciSifre")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("web_proje.Entity.Nobet", b =>
                {
                    b.Property<int>("NobetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NobetId"));

                    b.Property<int>("AsistanId")
                        .HasColumnType("int");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Nobet_Tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("NobetId");

                    b.ToTable("Nobetler");
                });

            modelBuilder.Entity("web_proje.Entity.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuId"));

                    b.Property<int>("AsistanId")
                        .HasColumnType("int");

                    b.Property<int>("HocaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Randevu_Tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("web_proje.Entity.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Roller");
                });
#pragma warning restore 612, 618
        }
    }
}
